minor text edits
uqmars/MARS-Subject-Guide pull request #17
Opened 2022-12-17 04:44 UTC by lambdanon

2022-12-17 11:44 UTC, q-horton requested changes
BE/ME change is good. Prerequisites have come directly from the source, and just lay out expected knowledge, so it's not great to suggest that it's only needed if you're in a specific specialisation. Perhaps just swap to a recommended prerequisite if you're trying to shift focus to those in the required course list.

2022-12-18 01:07 UTC, lambdanon commented
hmm I guess i'll just have another small section for recommended prerequisites. ill have a look at the other courses if they also have recommended prereqs and fill those in as well.

2022-12-18 02:49 UTC, q-horton requested changes
Just a couple small things, otherwise lgtm

2022-12-18 02:49 UTC, q-horton commented on 2023/chapters/Electives.tex
> +        \item \hyperlink{CCSE4011}{CSSE4011}
CCSE -> CSSE

2022-12-18 02:49 UTC, q-horton commented on 2023/chapters/Electives.tex
> +        \item \hyperlink{CSSE3010}{CSSE3010}
This is the first item in the list

2022-12-18 04:15 UTC, lambdanon commented on 2023/chapters/Electives.tex
> +        \item \hyperlink{CCSE4011}{CSSE4011}
oh i swear i fixed that lmao

2022-12-18 04:19 UTC, lambdanon commented on 2023/chapters/Electives.tex
> +        \item \hyperlink{CSSE3010}{CSSE3010}
nah its not, thats for software engg. ill fix up the other mistake

2022-12-18 04:20 UTC, merged

2022-12-18 04:23 UTC, q-horton commented on 2023/chapters/Electives.tex
> +        \item \hyperlink{CSSE3010}{CSSE3010}
Ah yea, whoops, didn't notice the compression in the middle lol